---
- name: Setup web server with PHP, MongoDB driver, and Apache2 on Ubuntu 24.04 LTS
  hosts: webservers
  become: yes

  vars:
    domain_name: mongo.bibhtech.in
    document_root: /var/www/wwwroot
    email_address: your-email@example.com  # Add your email address here

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Add ondrej/php PPA for PHP packages
      apt_repository:
        repo: ppa:ondrej/php

    - name: Install necessary packages
      apt:
        name:
          - apache2
          - php8.0
          - php8.0-mongodb
          - libapache2-mod-php8.0
          - certbot
          - python3-certbot-apache
        state: present

    - name: Enable Apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - rewrite
        - ssl

    - name: Create document root directory
      file:
        path: "{{ document_root }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Create a virtual host configuration file for HTTP
      copy:
        dest: /etc/apache2/sites-available/{{ domain_name }}.conf
        content: |
          <VirtualHost *:80>
              ServerAdmin webmaster@{{ domain_name }}
              ServerName {{ domain_name }}
              DocumentRoot {{ document_root }}

              <Directory {{ document_root }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/{{ domain_name }}-error.log
              CustomLog ${APACHE_LOG_DIR}/{{ domain_name }}-access.log combined

              # Redirect HTTP to HTTPS
              RewriteEngine on
              RewriteCond %{SERVER_NAME} ={{ domain_name }}
              RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
          </VirtualHost>

    - name: Enable the virtual host
      command: a2ensite {{ domain_name }}.conf

    - name: Reload Apache to apply changes
      service:
        name: apache2
        state: reloaded

    - name: Obtain SSL certificate from Let's Encrypt
      shell: >
        certbot --apache --agree-tos --no-eff-email --email {{ email_address }} --non-interactive --redirect
        -d {{ domain_name }}
      register: certbot_result
      ignore_errors: yes

    - name: Debug certbot output
      debug:
        var: certbot_result

    - name: Create SSL virtual host configuration
      copy:
        dest: /etc/apache2/sites-available/{{ domain_name }}-ssl.conf
        content: |
          <VirtualHost *:443>
              ServerAdmin webmaster@{{ domain_name }}
              ServerName {{ domain_name }}
              DocumentRoot {{ document_root }}

              <Directory {{ document_root }}>
                  Options Indexes FollowSymLinks
                  AllowOverride All
                  Require all granted
              </Directory>

              ErrorLog ${APACHE_LOG_DIR}/{{ domain_name }}-error.log
              CustomLog ${APACHE_LOG_DIR}/{{ domain_name }}-access.log combined

              SSLEngine on
              SSLCertificateFile /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
              SSLCertificateKeyFile /etc/letsencrypt/live/{{ domain_name }}/privkey.pem
              Include /etc/letsencrypt/options-ssl-apache.conf
          </VirtualHost>

    - name: Enable SSL virtual host
      command: a2ensite {{ domain_name }}-ssl.conf
      when: certbot_result.rc == 0

    - name: Reload Apache to apply changes
      service:
        name: apache2
        state: reloaded
      when: certbot_result.rc == 0
